"""
main.py

Sub-step 20 (Phase 5), extended at sub-step 21: the first slice of the
HLD's L1 Presentation layer -- a single FastAPI process serving the API
routes for the full pipeline built in agents/:
uploaded resume file -> extract_resume_text -> run_agent1 (match +
blueprint) -> generate_questions_for_blueprint (Agent 2, question
generation + self-check) -> score_assessment (Agent 3, scoring the
candidate's selected answers).

Single process, no separate frontend build step, no infra provisioning --
matches the HLD's stated constraints. Returns plain JSON.

Security controls (Hackfest secure-coding guidelines):
  - every /api route requires a bearer token (TALENT360_BACKEND_TOKEN),
    compared in constant time; fails closed outside debug mode
  - upload allowlist + size cap + magic-byte check, random temp file name
  - strict request-model validation (types, ranges, id patterns, sizes)
  - per-client rate limiting (DoS / cost control for LLM-backed routes)
  - errors never echo exception text, provider URLs or stack traces
  - security headers + no-store caching on API responses
  - audit trail for every API call (logs/audit.jsonl)
  - AI-generated output is labelled and flagged for human review
"""

import logging
import os
import re
import sys
import tempfile
import threading
import time
from collections import defaultdict, deque
from pathlib import Path

from typing import Annotated, Any, Literal

from fastapi import Depends, FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi import Path as PathParam
from fastapi import Query
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, field_validator
from dotenv import load_dotenv

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent
AGENTS_DIR = PROJECT_ROOT / "agents"
sys.path.insert(0, str(AGENTS_DIR))

# Load .env before any agent module is imported: security.py reads its
# limits and TALENT360_LOG_DIR at import time.
load_dotenv(PROJECT_ROOT / ".env")

import security  # noqa: E402
from resume_parser import extract_resume_text  # noqa: E402
from agents1 import run_agent1  # noqa: E402
from agent1_blueprint import build_blueprint, with_assessment_level  # noqa: E402
from agent2_question import generate_questions_for_blueprint  # noqa: E402
from agent3_scoring import score_assessment  # noqa: E402
from agent4_evidence import (  # noqa: E402
    MAX_TRANSCRIPT_TURNS, SimulationInputError, generate_case_studies_for_assessment, generate_evidence_report,
    next_probe,
)
from agent5_devplan import run_agent5, run_agent5_from_score, build_dev_dashboard  # noqa: E402
from agent5_outline import MAX_ITEMS as OUTLINE_MAX_ITEMS, OutlineInputError, build_training_outline  # noqa: E402

log = logging.getLogger("talent360i.api")

DEBUG_MODE = os.getenv("TALENT360_DEBUG", "true").lower() in {"1", "true", "yes", "development"}
API_TOKEN = os.getenv("TALENT360_BACKEND_TOKEN", "")
if not API_TOKEN and not DEBUG_MODE:
    raise RuntimeError("TALENT360_BACKEND_TOKEN must be configured when TALENT360_DEBUG is disabled")
if not API_TOKEN:
    log.warning("TALENT360_BACKEND_TOKEN is not set: API authentication is DISABLED (debug mode only).")

AI_DISCLOSURE = (
    "This content was generated by an AI system and must be reviewed by a human "
    "before it is used for any decision about a person."
)

# Docs/OpenAPI expose the full attack surface -- debug only.
app = FastAPI(
    title="Talent 360i -- Resume Assessment Pipeline API",
    docs_url="/docs" if DEBUG_MODE else None,
    redoc_url=None,
    openapi_url="/openapi.json" if DEBUG_MODE else None,
)

STATIC_DIR = APP_DIR / "static"
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

# ---------------------------------------------------------------------------
# Authentication, rate limiting, headers, audit
# ---------------------------------------------------------------------------

_ID_RE = r"^[A-Za-z0-9_\-]{1,100}$"

_RATE_LIMITS = {  # path prefix -> (max requests, window seconds) per client
    "/api/generate": (10, 60),
    "/api/case-studies": (20, 60),
    "/api/evidence": (20, 60),
    "/api/simulation": (60, 60),
    "/api/match": (20, 60),
    "/api/devplan": (20, 60),
    "/api/training-outline": (20, 60),
    "/api/score": (60, 60),
}
_DEFAULT_LIMIT = (60, 60)
_hits: dict[str, deque] = defaultdict(deque)
_hits_lock = threading.Lock()


def _client_id(request: Request) -> str:
    return request.client.host if request.client else "unknown"


def _rate_limited(request: Request) -> bool:
    path = request.url.path
    limit, window = next((v for k, v in _RATE_LIMITS.items() if path.startswith(k)), _DEFAULT_LIMIT)
    key = f"{_client_id(request)}:{path.split('/')[2] if path.count('/') > 1 else path}"
    now = time.monotonic()
    with _hits_lock:
        bucket = _hits[key]
        while bucket and now - bucket[0] > window:
            bucket.popleft()
        if len(bucket) >= limit:
            return True
        bucket.append(now)
    return False


def require_api_token(request: Request) -> None:
    """Bearer-token gate for every /api route (broken-access-control control)."""
    if not API_TOKEN:  # debug mode only -- startup refuses this otherwise
        return
    header = request.headers.get("authorization", "")
    scheme, _, supplied = header.partition(" ")
    if scheme.lower() != "bearer" or not security.token_matches(supplied.strip(), API_TOKEN):
        security.audit(
            "auth_failed", actor=_client_id(request), outcome="denied",
            resource=request.url.path, details={"reason": "missing or invalid bearer token"},
        )
        raise HTTPException(status_code=401, detail="Authentication required")


@app.middleware("http")
async def api_guard(request: Request, call_next):
    path = request.url.path
    started = time.monotonic()

    if path.startswith("/api/") and _rate_limited(request):
        security.audit("rate_limited", actor=_client_id(request), outcome="http_429", resource=path)
        return JSONResponse(status_code=429, content={"message": "Too many requests. Please slow down."},
                            headers={"Retry-After": "60"})

    response = await call_next(request)

    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Content-Security-Policy"] = "default-src 'none'; frame-ancestors 'none'"
    if not DEBUG_MODE:
        response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
    if path.startswith("/api/"):
        response.headers["Cache-Control"] = "no-store"
        security.audit(
            "api_call", actor=_client_id(request), resource=f"{request.method} {path}",
            outcome="success" if response.status_code < 400 else f"http_{response.status_code}",
            details={"ms": int((time.monotonic() - started) * 1000)},
        )
    return response


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"message": str(exc.detail)})


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    # Safety net: guarantees JSON always comes back (every frontend caller
    # does res.json() on error paths) WITHOUT echoing exception text, which
    # can carry file paths, SQL, provider URLs or key fragments. The detail
    # goes to the server log only.
    log.exception("Unhandled error on %s", request.url.path)
    security.audit("unhandled_error", actor=_client_id(request), outcome="http_500",
                   resource=request.url.path, details={"type": type(exc).__name__})
    return JSONResponse(status_code=500, content={"message": "Unexpected server error."})


def _ai_unavailable(exc: Exception, what: str) -> JSONResponse:
    """503 without leaking provider endpoints / internal messages to the caller."""
    log.warning("%s failed: %s", what, security.redact(exc))
    security.audit("ai_unavailable", outcome="http_503", resource=what, details={"error": security.redact(exc)})
    return JSONResponse(
        status_code=503,
        content={"message": "The AI service is temporarily unavailable. Please try again shortly."},
    )


def _label_ai(payload: dict) -> dict:
    """Transparency + human-oversight markers on every AI-produced response."""
    if isinstance(payload, dict):
        payload["ai_generated"] = True
        payload["ai_disclosure"] = AI_DISCLOSURE
        payload["human_review_required"] = True
    return payload


# Tower -> framework display mapping. AP and O2C are the FinOps-framework
# towers with complete skill_master/role_skill_map data; R2R is the
# RD-framework tower, which is a documented data gap (see
# scripts/build_sqlite.py's load_skill_master docstring) -- every R2R
# role_skill_map row is missing behavior_indicator/capability, so Agent 2
# will skip all of its skills today rather than generate ungrounded
# questions. Not a bug here -- the presentation layer just labels it.
TOWER_FRAMEWORK = {"AP": "FinOps", "O2C": "FinOps", "R2R": "RD"}


@app.get("/")
def index():
    # The page routes that used to serve app/static/*.html directly are
    # retired -- the Talent360i portal (a separate process) is now the
    # browser-facing frontend for this pipeline; this process is API-only.
    return JSONResponse({"message": "Talent 360i pipeline API. See the Talent360i portal for the UI."})


def _blueprint_summary(blueprint):
    return {
        "role_id": blueprint["role_id"],
        "role_name": blueprint["role_name"],
        "tower": blueprint["tower"],
        "framework": TOWER_FRAMEWORK.get(blueprint["tower"], blueprint["tower"]),
        "role_grade": blueprint["role_grade"],
        "skill_count": blueprint["skill_count"],
        "target_question_count": blueprint["target_question_count"],
    }


async def _match_uploaded_resume(file: UploadFile):
    """Upload -> validated text -> Agent 1. Returns (agent1_result, None) or (None, error JSONResponse)."""
    # Read at most limit+1 bytes so an oversized upload can't exhaust memory.
    data = await file.read(security.MAX_UPLOAD_BYTES + 1)
    try:
        safe_name = security.validate_upload(file.filename, data)
    except security.ValidationError as exc:
        return None, JSONResponse(status_code=400, content={"status": "invalid_upload", "message": str(exc)})

    # Random temp name (never the user-supplied one); only the vetted
    # extension is kept so the parser can dispatch on it.
    suffix = Path(safe_name).suffix.lower()
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(data)
        tmp_path = tmp.name

    try:
        try:
            resume_text = extract_resume_text(tmp_path)
        except (FileNotFoundError, ValueError):
            return None, JSONResponse(
                status_code=400,
                content={
                    "status": "extraction_failed",
                    "message": "No readable text could be extracted from this file. Upload a text-based PDF, DOCX or TXT resume.",
                },
            )
        except Exception as exc:  # malformed/hostile PDF or DOCX: parser libraries raise many types
            log.warning("Resume parsing failed: %s", security.redact(exc))
            return None, JSONResponse(
                status_code=400,
                content={"status": "extraction_failed", "message": "The file could not be parsed as a valid resume."},
            )

        # Character-set + length restriction on the only free-form text that
        # reaches embeddings / prompts (guideline G).
        resume_text = security.sanitize_prompt_text(resume_text, security.MAX_RESUME_CHARS)
        if not resume_text:
            return None, JSONResponse(
                status_code=400,
                content={"status": "extraction_failed", "message": "The resume contained no usable text."},
            )
        flags = security.detect_injection(resume_text)
        if flags:
            security.audit("prompt_injection_suspected", actor="A1", outcome="flagged", stream="llm",
                           resource="resume_upload", details={"indicators": flags})
        return run_agent1(resume_text), None
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def _unmatched_response(agent1_result):
    """The non-auto_matched outcomes, shared by /api/generate and /api/match (None when auto_matched)."""
    status = agent1_result["status"]
    if status == "no_match_found":
        return {"status": status, "message": "No role matched this resume closely enough to proceed."}
    if status == "blueprint_unavailable":
        top = agent1_result["match_info"]["top_match"]
        return {
            "status": status,
            "message": (
                f"Matched role_id '{top['role_id']}' but no blueprint could be built "
                "(likely a reference-only role with no role_master entry)."
            ),
        }
    if status == "needs_human_confirmation":
        candidates = [
            _blueprint_summary(bp)
            for bp in agent1_result["candidate_blueprints"]
            if bp["success"]
        ]
        return _label_ai({
            "status": status,
            "gap": agent1_result["match_info"]["gap"],
            "candidates": candidates,
            "message": "Two roles matched closely -- human confirmation needed before generating questions.",
        })
    return None


@app.post("/api/match", dependencies=[Depends(require_api_token)])
async def match(file: Annotated[UploadFile, File(...)]):
    """Resume -> matched role only (Agent 1, embeddings, no LLM). The SME then
    decides how many questions and at what level (see /api/generate-for-role)."""
    agent1_result, error = await _match_uploaded_resume(file)
    if error:
        return error
    unmatched = _unmatched_response(agent1_result)
    if unmatched:
        return unmatched
    return _label_ai({"status": "auto_matched", "match": _blueprint_summary(agent1_result["blueprint"])})


@app.post("/api/generate", dependencies=[Depends(require_api_token)])
async def generate(
    file: Annotated[UploadFile, File(...)],
    max_items: Annotated[int, Form(ge=1, le=10)] = 5,
):
    agent1_result, error = await _match_uploaded_resume(file)
    if error:
        return error
    unmatched = _unmatched_response(agent1_result)
    if unmatched:
        return unmatched

    # auto_matched
    blueprint = agent1_result["blueprint"]
    summary = _blueprint_summary(blueprint)

    try:
        question_result = generate_questions_for_blueprint(blueprint, max_items=max_items)
    except (RuntimeError, ValueError) as exc:
        log.warning("Question generation failed: %s", security.redact(exc))
        return {
            "status": "questions_unavailable",
            "match": summary,
            "message": "Questions could not be generated right now. Please try again shortly.",
        }

    return _label_ai({
        "status": "auto_matched",
        "match": summary,
        "items": question_result["items"],
        "skills_skipped": question_result["skills_skipped"],
        "counts": question_result["counts"],
    })


class GenerateForRoleRequest(BaseModel):
    # The SME's assessment design: which role, how many questions, at what
    # proficiency level (None = each skill's own role target), optionally
    # only for some of the role's skills.
    role_id: str = Field(pattern=_ID_RE)
    max_items: int = Field(ge=1, le=10)
    level: int | None = Field(default=None, ge=1, le=5)
    skills: list[Annotated[str, Field(max_length=200)]] | None = Field(default=None, max_length=20)


@app.post("/api/generate-for-role", dependencies=[Depends(require_api_token)])
async def generate_for_role(payload: GenerateForRoleRequest):
    blueprint = build_blueprint(payload.role_id)
    if not blueprint["success"]:
        return JSONResponse(status_code=400, content={"message": "Unknown role."})
    if payload.level:
        blueprint = with_assessment_level(blueprint, payload.level)
    if payload.skills:
        wanted = set(payload.skills)
        blueprint = {**blueprint, "skills": [s for s in blueprint["skills"] if s["skill"] in wanted]}
    try:
        result = generate_questions_for_blueprint(blueprint, max_items=payload.max_items)
    except (RuntimeError, ValueError) as exc:
        return _ai_unavailable(exc, "generate-for-role")
    return _label_ai({
        "status": "generated", "match": _blueprint_summary(blueprint), "level": payload.level,
        "items": result["items"], "skills_skipped": result["skills_skipped"], "counts": result["counts"],
    })


# ---------------------------------------------------------------------------
# Request models: whitelist validation for every field a client can send.
# ---------------------------------------------------------------------------

MAX_ITEMS_PER_REQUEST = 50
_OPTION_RE = re.compile(r"^[A-Da-d]$")


def _validate_answers(answers: dict[str, str]) -> dict[str, str]:
    if len(answers) > MAX_ITEMS_PER_REQUEST:
        raise ValueError("Too many answers.")
    for key, value in answers.items():
        if len(key) > 100:
            raise ValueError("Answer key too long.")
        if len(value) > security.MAX_ANSWER_CHARS:
            raise ValueError("Answer too long.")
    return answers


class ScoreRequest(BaseModel):
    # items are the exact objects /api/generate returned -- the frontend
    # holds them in memory and posts them back alongside the candidate's
    # answers, since there's no server-side session store for this demo.
    items: list[dict[str, Any]] = Field(max_length=MAX_ITEMS_PER_REQUEST)
    answers: dict[str, str]

    @field_validator("answers")
    @classmethod
    def _check_answers(cls, answers):
        _validate_answers(answers)
        # /api/score takes multiple-choice selections only.
        for value in answers.values():
            if value and not _OPTION_RE.match(value):
                raise ValueError("MCQ answers must be A, B, C or D.")
        return answers


@app.post("/api/score", dependencies=[Depends(require_api_token)])
async def score(payload: ScoreRequest):
    try:
        return score_assessment(payload.items, payload.answers)
    except (KeyError, TypeError, ValueError):
        return JSONResponse(status_code=400, content={"message": "The submitted items or answers are malformed."})


class CaseStudyRequest(BaseModel):
    role_id: str = Field(pattern=_ID_RE)
    # Agent 3's report -- "take the report and analysis generated by
    # Agent 3" is exactly what select_focus_skills() does with this.
    score: dict[str, Any]
    max_questions: int = Field(default=3, ge=1, le=5)


@app.post("/api/case-studies", dependencies=[Depends(require_api_token)])
async def case_studies(payload: CaseStudyRequest):
    blueprint = build_blueprint(payload.role_id)
    if not blueprint["success"]:
        return JSONResponse(status_code=400, content={"message": "Unknown role."})

    try:
        result = generate_case_studies_for_assessment(payload.score, blueprint, max_questions=payload.max_questions)
    except (RuntimeError, ValueError) as exc:
        return _ai_unavailable(exc, "case-studies")

    return _label_ai(result)


class TurnMeta(BaseModel):
    # Portal telemetry for one candidate response, used by the integrity check.
    paste_chars: int | None = Field(default=None, ge=0, le=100_000)
    paste_events: int | None = Field(default=None, ge=0, le=1_000)
    active_seconds: int | None = Field(default=None, ge=0, le=86_400)


class TranscriptTurn(BaseModel):
    role: Literal["agent", "candidate"]
    text: str = Field(max_length=security.MAX_ANSWER_CHARS)
    meta: TurnMeta | None = None


Transcript = Annotated[list[TranscriptTurn], Field(max_length=MAX_TRANSCRIPT_TURNS)]


class ProbeRequest(BaseModel):
    # One step of the simulation: the simulation object /api/case-studies
    # returned plus the conversation so far, held by the caller -- same
    # stateless pattern as /api/score.
    case_study: dict[str, Any]
    transcript: Transcript = Field(min_length=1)


@app.post("/api/simulation/probe", dependencies=[Depends(require_api_token)])
async def simulation_probe(payload: ProbeRequest):
    try:
        result = next_probe(payload.case_study, [t.model_dump(exclude_none=True) for t in payload.transcript])
    except SimulationInputError:
        return JSONResponse(status_code=400, content={"message": "The simulation or transcript is malformed."})
    except (RuntimeError, ValueError) as exc:
        return _ai_unavailable(exc, "simulation-probe")
    return _label_ai(result)


class EvidenceRequest(BaseModel):
    # case_studies are the exact objects /api/case-studies returned,
    # held client-side and posted back with the answers -- same
    # stateless pattern as /api/score. transcripts (optional) carries the
    # full probed conversation per simulation, keyed by question_id.
    case_studies: list[dict[str, Any]] = Field(max_length=10)
    answers: dict[str, str]
    transcripts: dict[str, Transcript] | None = Field(default=None, max_length=10)
    score: dict[str, Any]
    role_id: str = Field(pattern=_ID_RE)
    role_name: str = Field(max_length=200)
    role_grade: str = Field(max_length=50)

    @field_validator("answers")
    @classmethod
    def _check_answers(cls, answers):
        return _validate_answers(answers)


@app.post("/api/evidence", dependencies=[Depends(require_api_token)])
async def evidence(payload: EvidenceRequest):
    try:
        result = generate_evidence_report(
            payload.case_studies,
            payload.answers,
            payload.score,
            payload.role_name,
            payload.role_id,
            payload.role_grade,
            transcripts={
                qid: [t.model_dump(exclude_none=True) for t in turns] for qid, turns in (payload.transcripts or {}).items()
            },
        )
    except SimulationInputError:
        return JSONResponse(status_code=400, content={"message": "The submitted case studies are malformed."})
    except (RuntimeError, ValueError) as exc:
        return _ai_unavailable(exc, "evidence")
    except (KeyError, TypeError):
        return JSONResponse(status_code=400, content={"message": "The submitted case studies are malformed."})
    return _label_ai(result)


@app.get("/api/devplan/{user_id}", dependencies=[Depends(require_api_token)])
async def devplan(
    user_id: Annotated[str, PathParam(pattern=_ID_RE)],
    max_steps: Annotated[int | None, Query(ge=1, le=20)] = None,
):
    # Synthetic-cohort path -- gaps come straight from skill_gaps (loaded
    # by scripts/build_sqlite.py's load_skill_gaps() from Skill_Gaps_TNI),
    # not from a live assessment. See agents/agent5_devplan.py. Wrapped
    # through build_dev_dashboard() for the same Coursera-leads +
    # duration-estimate extras the live path gets below (no evidence
    # report exists for this synthetic path, so the duration estimate
    # falls back to gap severity alone).
    try:
        return _label_ai(build_dev_dashboard(run_agent5(user_id, max_steps=max_steps)))
    except (RuntimeError, ValueError) as exc:
        return _ai_unavailable(exc, "devplan")


class DevPlanFromScoreRequest(BaseModel):
    # Live-pipeline path: score is Agent 3's report and role_id identifies
    # the blueprint to rebuild -- same "take Agent 3's own report" pattern
    # as CaseStudyRequest above, so a resume-driven candidate (with no row
    # in skill_gaps) still gets a development plan. evidence is Agent 4's
    # own report (optional -- the button on the evidence page always has
    # one, but the endpoint doesn't require the case-study round to have
    # happened) and feeds estimate_remediation_duration()'s compatibility
    # band; without it, the duration estimate falls back to score's own
    # overall_score_pct.
    role_id: str = Field(pattern=_ID_RE)
    score: dict[str, Any]
    evidence: dict[str, Any] | None = None
    max_steps: int | None = Field(default=None, ge=1, le=20)


@app.post("/api/devplan", dependencies=[Depends(require_api_token)])
async def devplan_from_score(payload: DevPlanFromScoreRequest):
    blueprint = build_blueprint(payload.role_id)
    if not blueprint["success"]:
        return JSONResponse(status_code=400, content={"message": "Unknown role."})

    try:
        plan_result = run_agent5_from_score(payload.score, blueprint, max_steps=payload.max_steps)
        return _label_ai(build_dev_dashboard(
            plan_result,
            evidence_report=payload.evidence,
            mcq_score_pct=payload.score.get("overall_score_pct"),
        ))
    except (RuntimeError, ValueError) as exc:
        return _ai_unavailable(exc, "devplan")


class OutlineItem(BaseModel):
    skill: str = Field(min_length=1, max_length=200)
    from_level: int | None = Field(default=None, ge=0, le=5)
    to_level: int = Field(ge=1, le=5)
    # Agent 4's "missing element" for this skill -- derived from candidate
    # text, so agent5_outline wraps it as untrusted data in the prompt.
    evidence_note: str | None = Field(default=None, max_length=300)


class TrainingOutlineRequest(BaseModel):
    # Only skills and levels: no name, transcript or resume leaves the portal.
    role_id: str = Field(pattern=_ID_RE)
    mode: Literal["gap", "skill_up"]
    items: list[OutlineItem] = Field(min_length=1, max_length=OUTLINE_MAX_ITEMS)


@app.post("/api/training-outline", dependencies=[Depends(require_api_token)])
async def training_outline(payload: TrainingOutlineRequest):
    """Agent 5's training-session outline after a manager decision. Never
    fails on the LLM: an unverifiable or unavailable model falls back to a
    labelled template outline."""
    try:
        result = build_training_outline(payload.role_id, payload.mode, [i.model_dump() for i in payload.items])
    except OutlineInputError as exc:
        return JSONResponse(status_code=400, content={"message": str(exc)})
    return _label_ai(result)
